const reviews = [
  {
    'reviewId': '0',
    'origin': 'Iringa, Tanzania',
    'destination': 'Dar es Salaam, Tanzania',
    'company': 'Abood',
    'price': 18000,
    'comment': 'The bus had an hour switch over in Morogoro.',
    'features': {
      'isAC': false,
      'isMusicVideos': true,
      'isMovies': false,
      'hasCurtains': false,
      'hasUSB': true,
      'brokedown': true,
    },
    'ticket_time': {'hours': 6, 'minutes': 0, 'AM': true},
    'departure_time': {'hours': 6, 'minutes': 10, 'AM': true},
    'arrival_time': {'hours': 7, 'minutes': 20, 'AM': false},
  },
  {
    'reviewId': '1',
    'origin': 'Iringa, Tanzania',
    'destination': 'Mwanza, Tanzania',
    'company': 'Upendo',
    'price': 40000,
    'comment': 'This took soooooo long! Get a snack in Singida. Also you can find a maps.me pin her here here here hereh ehrehrehr ehereh herer',
    'features': {
      'isAC': false,
      'isMusicVideos': false,
      'isMovies': false,
      'hasCurtains': false,
      'hasUSB': true,
      'brokedown': false,
    },
    'ticket_time': {'hours': 7, 'minutes': 0, 'AM': true},
    'departure_time': {'hours': 7, 'minutes': 0, 'AM': true},
    'arrival_time': {'hours': 10, 'minutes': 0, 'AM': false},
  },
  {
    'reviewId': '2',
    'origin': 'Tanga, Tanzania',
    'destination': 'Dar es Salaam, Tanzania',
    'company': 'Shatco',
    'price': 15000,
    'comment': 'Super cheap!',
    'features': {
      'isAC': false,
      'isMusicVideos': false,
      'isMovies': true,
      'hasCurtains': true,
      'hasUSB': false,
      'brokedown': false,
    },
    'ticket_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'departure_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'arrival_time': {'hours': 12, 'minutes': 0, 'AM': false},
  },
  {
    'reviewId': '3',
    'origin': 'Mwanza, Tanzania',
    'destination': 'Arusha, Tanzania',
    'company': 'Abood',
    'price': 18000,
    'comment': '',
    'features': {
      'isAC': false,
      'isMusicVideos': true,
      'isMovies': false,
      'hasCurtains': false,
      'hasUSB': true,
      'brokedown': false,
    },
    'ticket_time': {'hours': 6, 'minutes': 0, 'AM': true},
    'departure_time': {'hours': 6, 'minutes': 10, 'AM': true},
    'arrival_time': {'hours': 7, 'minutes': 20, 'AM': false},
  },
  {
    'reviewId': '4',
    'origin': 'Morogoro, Tanzania',
    'destination': 'Dar es Salaam, Tanzania',
    'company': 'Upendo',
    'price': 40000,
    'comment': 'This took soooooo long! Get a snack in Singida. Also you can find a maps.me pin her here here here hereh ehrehrehr ehereh herer',
    'features': {
      'isAC': false,
      'isMusicVideos': false,
      'isMovies': false,
      'hasCurtains': false,
      'hasUSB': true,
      'brokedown': false,
    },
    'ticket_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'departure_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'arrival_time': {'hours': 12, 'minutes': 0, 'AM': false},
  },
  {
    'reviewId': '5',
    'origin': 'Morogoro, Tanzania',
    'destination': 'Dar es Salaam, Tanzania',
    'company': 'Shatco',
    'price': 15000,
    'comment': 'Super cheap!',
    'features': {
      'isAC': false,
      'isMusicVideos': false,
      'isMovies': true,
      'hasCurtains': true,
      'hasUSB': false,
      'brokedown': false,
    },
    'ticket_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'departure_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'arrival_time': {'hours': 12, 'minutes': 0, 'AM': false},
  },
  {
    'reviewId': '6',
    'origin': 'Dar es Salaam, Tanzania',
    'destination': 'Morogoro, Tanzania',
    'company': 'Shatco',
    'price': 15000,
    'comment': 'Super cheap!',
    'features': {
      'isAC': false,
      'isMusicVideos': false,
      'isMovies': true,
      'hasCurtains': true,
      'hasUSB': false,
      'brokedown': false,
    },
    'ticket_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'departure_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'arrival_time': {'hours': 12, 'minutes': 0, 'AM': false},
  },
]

export default reviews;
