const reviews = [
  {
    'reviewId': '0',
    'origin': 'Iringa, Tanzania',
    'destination': 'Dar es Salaam, Tanzania',
    'company': 'Abood',
    'price': 18000,
    'comment': 'The bus had an hour switch over in Morogoro.',
    'features': {
      'isAC': false,
      'isMusicVideos': true,
      'isMovies': false,
      'hasCurtains': false,
      'hasUSB': false,
      'brokedown': false,
    },
    'ticket_time': {'hours': 6, 'minutes': 0, 'AM': true},
    'departure_time': {'hours': 6, 'minutes': 10, 'AM': true},
    'arrival_time': {'hours': 7, 'minutes': 20, 'AM': false},
  },
  {
    'reviewId': '1',
    'origin': 'Iringa, Tanzania',
    'destination': 'Mwanza, Tanzania',
    'company': 'Upendo',
    'price': 40000,
    'comment': 'This took soooooo long! Get a snack in Singida.',
    'features': {
      'isAC': false,
      'isMusicVideos': false,
      'isMovies': false,
      'hasCurtains': false,
      'hasUSB': false,
      'brokedown': false,
    },
    'ticket_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'departure_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'arrival_time': {'hours': 12, 'minutes': 0, 'AM': false},
  },
  {
    'reviewId': '2',
    'origin': 'Tanga, Tanzania',
    'destination': 'Dar es Salaam, Tanzania',
    'company': 'Shatco',
    'price': 15000,
    'comment': 'Super cheap!',
    'features': {
      'isAC': false,
      'isMusicVideos': false,
      'isMovies': false,
      'hasCurtains': false,
      'hasUSB': false,
      'brokedown': false,
    },
    'ticket_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'departure_time': {'hours': 12, 'minutes': 0, 'AM': false},
    'arrival_time': {'hours': 12, 'minutes': 0, 'AM': false},
  },
]

export default reviews;
